server:
  port: 8091

spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/cooperate-editor?serverTimezone=Asia/Shanghai&useSSL=false
  redis:
    host: 192.168.20.129
    port: 6379
    database: 1
    password: redis
