server:
  port: 8091

spring:
  datasource:
    password: 123456
    username: wikiUser
    url: jdbc:mysql://localhost:3306/wiki?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.20.129
    port: 6379
    database: 1
    password: redis

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  # 打印所有的sql日志，sql，参数，结果
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



